(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require bool.Bool.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.
Require real.Real.
Require real.RealInfix.
Require real.FromInt.
Require map.Map.

Parameter eqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom eqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  ((x = y) -> ((eqb x y) = Init.Datatypes.true)) /\
  (~ (x = y) -> ((eqb x y) = Init.Datatypes.false)).

Parameter neqb:
  forall {a:Type} {a_WT:WhyType a}, a -> a -> Init.Datatypes.bool.

Axiom neqb'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (x:a) (y:a),
  (~ (x = y) -> ((neqb x y) = Init.Datatypes.true)) /\
  ((x = y) -> ((neqb x y) = Init.Datatypes.false)).

Parameter zlt: Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zlt'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x < y)%Z -> ((zlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%Z -> ((zlt x y) = Init.Datatypes.false)).

Parameter zleq:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Init.Datatypes.bool.

Axiom zleq'def :
  forall (x:Numbers.BinNums.Z) (y:Numbers.BinNums.Z),
  ((x <= y)%Z -> ((zleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%Z -> ((zleq x y) = Init.Datatypes.false)).

Parameter rlt:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rlt'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x < y)%R -> ((rlt x y) = Init.Datatypes.true)) /\
  (~ (x < y)%R -> ((rlt x y) = Init.Datatypes.false)).

Parameter rleq:
  Reals.Rdefinitions.R -> Reals.Rdefinitions.R -> Init.Datatypes.bool.

Axiom rleq'def :
  forall (x:Reals.Rdefinitions.R) (y:Reals.Rdefinitions.R),
  ((x <= y)%R -> ((rleq x y) = Init.Datatypes.true)) /\
  (~ (x <= y)%R -> ((rleq x y) = Init.Datatypes.false)).

(* Why3 assumption *)
Definition real_of_int (x:Numbers.BinNums.Z) : Reals.Rdefinitions.R :=
  BuiltIn.IZR x.

Axiom c_euclidian :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z), ~ (d = 0%Z) ->
  (n = (((ZArith.BinInt.Z.quot n d) * d)%Z + (ZArith.BinInt.Z.rem n d))%Z).

Axiom cmod_remainder :
  forall (n:Numbers.BinNums.Z) (d:Numbers.BinNums.Z),
  ((0%Z <= n)%Z -> (0%Z < d)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) < d)%Z) /\
  ((n <= 0%Z)%Z -> (0%Z < d)%Z ->
   ((-d)%Z < (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z) /\
  ((0%Z <= n)%Z -> (d < 0%Z)%Z ->
   (0%Z <= (ZArith.BinInt.Z.rem n d))%Z /\
   ((ZArith.BinInt.Z.rem n d) < (-d)%Z)%Z) /\
  ((n <= 0%Z)%Z -> (d < 0%Z)%Z ->
   (d < (ZArith.BinInt.Z.rem n d))%Z /\ ((ZArith.BinInt.Z.rem n d) <= 0%Z)%Z).

Axiom cdiv_neutral :
  forall (a:Numbers.BinNums.Z), ((ZArith.BinInt.Z.quot a 1%Z) = a).

Axiom cdiv_inv :
  forall (a:Numbers.BinNums.Z), ~ (a = 0%Z) ->
  ((ZArith.BinInt.Z.quot a a) = 1%Z).

Axiom cdiv_closed_remainder :
  forall (a:Numbers.BinNums.Z) (b:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  (0%Z <= a)%Z -> (0%Z <= b)%Z ->
  (0%Z <= (b - a)%Z)%Z /\ ((b - a)%Z < n)%Z ->
  ((ZArith.BinInt.Z.rem a n) = (ZArith.BinInt.Z.rem b n)) -> (a = b).

(* Why3 assumption *)
Inductive addr :=
  | addr'mk : Numbers.BinNums.Z -> Numbers.BinNums.Z -> addr.
Axiom addr_WhyType : WhyType addr.
Existing Instance addr_WhyType.

(* Why3 assumption *)
Definition base (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x
  end.

(* Why3 assumption *)
Definition offset (v:addr) : Numbers.BinNums.Z :=
  match v with
  | addr'mk x x1 => x1
  end.

(* Why3 assumption *)
Definition malloc := Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition null : addr := addr'mk 0%Z 0%Z.

(* Why3 assumption *)
Definition global (b:Numbers.BinNums.Z) : addr := addr'mk b 0%Z.

Parameter addr_le: addr -> addr -> Prop.

Parameter addr_lt: addr -> addr -> Prop.

Parameter addr_le_bool: addr -> addr -> Init.Datatypes.bool.

Parameter addr_lt_bool: addr -> addr -> Init.Datatypes.bool.

Axiom addr_le_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_le p q <-> ((offset p) <= (offset q))%Z.

Axiom addr_lt_def :
  forall (p:addr) (q:addr), ((base p) = (base q)) ->
  addr_lt p q <-> ((offset p) < (offset q))%Z.

Axiom addr_le_bool_def :
  forall (p:addr) (q:addr),
  addr_le p q <-> ((addr_le_bool p q) = Init.Datatypes.true).

Axiom addr_lt_bool_def :
  forall (p:addr) (q:addr),
  addr_lt p q <-> ((addr_lt_bool p q) = Init.Datatypes.true).

(* Why3 assumption *)
Definition shift (p:addr) (k:Numbers.BinNums.Z) : addr :=
  addr'mk (base p) ((offset p) + k)%Z.

(* Why3 assumption *)
Definition valid_rw (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  (0%Z < (base p))%Z /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_rd (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (0%Z < n)%Z ->
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\ (((offset p) + n)%Z <= (m (base p)))%Z.

(* Why3 assumption *)
Definition valid_obj (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr) :
    Prop :=
  ~ (0%Z = (base p)) /\
  (0%Z <= (offset p))%Z /\
  ((offset p) <= (m (base p)))%Z /\ (0%Z < (m (base p)))%Z.

(* Why3 assumption *)
Definition invalid (m:Numbers.BinNums.Z -> Numbers.BinNums.Z) (p:addr)
    (n:Numbers.BinNums.Z) : Prop :=
  (n <= 0%Z)%Z \/
  ((base p) = 0%Z) \/
  ((m (base p)) <= (offset p))%Z \/ (((offset p) + n)%Z <= 0%Z)%Z.

Axiom valid_rw_rd :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  forall (n:Numbers.BinNums.Z), valid_rw m p n -> valid_rd m p n.

Axiom valid_string :
  forall (m:Numbers.BinNums.Z -> Numbers.BinNums.Z), forall (p:addr),
  ((base p) < 0%Z)%Z ->
  (0%Z <= (offset p))%Z /\ ((offset p) < (m (base p)))%Z ->
  valid_rd m p 1%Z /\ ~ valid_rw m p 1%Z.

(* Why3 assumption *)
Definition included (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (0%Z < lp)%Z ->
  (0%Z <= lq)%Z /\
  ((base p) = (base q)) /\
  ((offset q) <= (offset p))%Z /\
  (((offset p) + lp)%Z <= ((offset q) + lq)%Z)%Z.

(* Why3 assumption *)
Definition separated (p:addr) (lp:Numbers.BinNums.Z) (q:addr)
    (lq:Numbers.BinNums.Z) : Prop :=
  (lp <= 0%Z)%Z \/
  (lq <= 0%Z)%Z \/
  ~ ((base p) = (base q)) \/
  (((offset q) + lq)%Z <= (offset p))%Z \/
  (((offset p) + lp)%Z <= (offset q))%Z.

Axiom separated_1 :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (i:Numbers.BinNums.Z)
    (j:Numbers.BinNums.Z),
  separated p lp q lq ->
  ((offset p) <= i)%Z /\ (i < ((offset p) + lp)%Z)%Z ->
  ((offset q) <= j)%Z /\ (j < ((offset q) + lq)%Z)%Z ->
  ~ ((addr'mk (base p) i) = (addr'mk (base q) j)).

Axiom separated_included :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z), (0%Z < lp)%Z ->
  (0%Z < lq)%Z -> separated p lp q lq -> ~ included p lp q lq.

Axiom included_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> included q lq r lr -> included p lp r lr.

Axiom separated_trans :
  forall (p:addr) (q:addr) (r:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z) (lr:Numbers.BinNums.Z),
  included p lp q lq -> separated q lq r lr -> separated p lp r lr.

Axiom separated_sym :
  forall (p:addr) (q:addr),
  forall (lp:Numbers.BinNums.Z) (lq:Numbers.BinNums.Z),
  separated p lp q lq <-> separated q lq p lp.

Parameter binit: Numbers.BinNums.Z -> Prop.

Parameter region: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter linked: (Numbers.BinNums.Z -> Numbers.BinNums.Z) -> Prop.

Parameter static_malloc: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition statically_allocated (base1:Numbers.BinNums.Z) : Prop :=
  (base1 = 0%Z) \/ (0%Z < (static_malloc base1))%Z.

Axiom valid_pointers_are_statically_allocated :
  forall (a:addr) (m:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (n:Numbers.BinNums.Z),
  (0%Z < n)%Z -> valid_rd m a n -> statically_allocated (base a).

Parameter int_of_addr: addr -> Numbers.BinNums.Z.

Parameter addr_of_int: Numbers.BinNums.Z -> addr.

Axiom addr_of_null : ((int_of_addr null) = 0%Z).

Axiom addr_of_int_bijection :
  forall (p:addr), statically_allocated (base p) ->
  ((addr_of_int (int_of_addr p)) = p).

Axiom table : Type.
Parameter table_WhyType : WhyType table.
Existing Instance table_WhyType.

Parameter table_of_base: Numbers.BinNums.Z -> table.

Parameter table_to_offset: table -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom table_to_offset_zero :
  forall (t:table), ((table_to_offset t 0%Z) = 0%Z).

Axiom table_to_offset_monotonic :
  forall (t:table), forall (o1:Numbers.BinNums.Z) (o2:Numbers.BinNums.Z),
  (o1 <= o2)%Z <-> ((table_to_offset t o1) <= (table_to_offset t o2))%Z.

Axiom Q_G_audit_log_4453_region : ((region 4454%Z) = 0%Z).

Axiom Q_G_audit_log_4453_linked :
  forall (t:Numbers.BinNums.Z -> Numbers.BinNums.Z), linked t ->
  ((t 4454%Z) = 103424%Z).

Axiom Q_G_audit_log_4453_binit : binit 4454%Z.

Parameter sconst: (addr -> Numbers.BinNums.Z) -> Prop.

(* Why3 assumption *)
Definition framed (m:addr -> addr) : Prop :=
  forall (p:addr), ((region (base p)) <= 0%Z)%Z ->
  ((region (base (m p))) <= 0%Z)%Z.

(* Why3 assumption *)
Definition scinit (m:addr -> Init.Datatypes.bool) : Prop :=
  forall (b:Numbers.BinNums.Z), binit b -> forall (p:addr), ((base p) = b) ->
  ((m p) = Init.Datatypes.true).

(* Why3 assumption *)
Definition eqmem {a:Type} {a_WT:WhyType a} (m1:addr -> a) (m2:addr -> a)
    (p:addr) (n:Numbers.BinNums.Z) : Prop :=
  forall (q:addr), included q 1%Z p n -> ((m1 q) = (m2 q)).

Parameter memcpy:
  forall {a:Type} {a_WT:WhyType a}, (addr -> a) -> addr -> (addr -> a) ->
  addr -> Numbers.BinNums.Z -> addr -> a.

Axiom memcpy'def :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (a0:addr) (m1:addr -> a) (a1:addr)
    (s:Numbers.BinNums.Z) (p:addr),
  (separated p 1%Z a0 s -> ((memcpy m0 a0 m1 a1 s p) = (m0 p))) /\
  (~ separated p 1%Z a0 s ->
   ((memcpy m0 a0 m1 a1 s p) =
    (let offset1 := (((offset a1) - (offset a0))%Z + (offset p))%Z in
     m1 (addr'mk (base a1) offset1)))).

Axiom eqmem_single :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  eqmem m1 m2 p 1%Z <-> ((m1 p) = (m2 p)).

Axiom eqmem_included :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr) (q:addr),
  forall (a1:Numbers.BinNums.Z) (b:Numbers.BinNums.Z), included p a1 q b ->
  eqmem m1 m2 q b -> eqmem m1 m2 p a1.

Axiom eqmem_sym :
  forall {a:Type} {a_WT:WhyType a},
  forall (m1:addr -> a) (m2:addr -> a), forall (p:addr),
  forall (a1:Numbers.BinNums.Z), eqmem m1 m2 p a1 -> eqmem m2 m1 p a1.

Axiom eqmem_update :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a), forall (v:a), forall (p:addr) (q:addr),
  forall (n':Numbers.BinNums.Z), separated p 1%Z q n' ->
  eqmem m0 (map.Map.set m0 p v) q n'.

Axiom eqmem_memcpy :
  forall {a:Type} {a_WT:WhyType a},
  forall (m0:addr -> a) (m1:addr -> a), forall (p:addr) (p':addr) (q:addr),
  forall (n:Numbers.BinNums.Z) (n':Numbers.BinNums.Z), separated p n p' n' ->
  eqmem m0 (memcpy m0 p m1 q n) p' n'.

(* Why3 assumption *)
Definition is_bool (x:Numbers.BinNums.Z) : Prop := (x = 0%Z) \/ (x = 1%Z).

(* Why3 assumption *)
Definition is_uint8 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 256%Z)%Z.

(* Why3 assumption *)
Definition is_sint8 (x:Numbers.BinNums.Z) : Prop :=
  ((-128%Z)%Z <= x)%Z /\ (x < 128%Z)%Z.

(* Why3 assumption *)
Definition is_uint16 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 65536%Z)%Z.

(* Why3 assumption *)
Definition is_sint16 (x:Numbers.BinNums.Z) : Prop :=
  ((-32768%Z)%Z <= x)%Z /\ (x < 32768%Z)%Z.

(* Why3 assumption *)
Definition is_uint32 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 4294967296%Z)%Z.

(* Why3 assumption *)
Definition is_sint32 (x:Numbers.BinNums.Z) : Prop :=
  ((-2147483648%Z)%Z <= x)%Z /\ (x < 2147483648%Z)%Z.

(* Why3 assumption *)
Definition is_uint64 (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < 18446744073709551616%Z)%Z.

(* Why3 assumption *)
Definition is_sint64 (x:Numbers.BinNums.Z) : Prop :=
  ((-9223372036854775808%Z)%Z <= x)%Z /\ (x < 9223372036854775808%Z)%Z.

Axiom is_bool0 : is_bool 0%Z.

Axiom is_bool1 : is_bool 1%Z.

Parameter to_bool: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_bool'def :
  forall (x:Numbers.BinNums.Z),
  ((x = 0%Z) -> ((to_bool x) = 0%Z)) /\ (~ (x = 0%Z) -> ((to_bool x) = 1%Z)).

Parameter to_uint8: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint8'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint8 x) = (to_uint8 (x + 256%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((256%Z <= x)%Z -> ((to_uint8 x) = (to_uint8 (x - 256%Z)%Z))) /\
   (~ (256%Z <= x)%Z -> ((to_uint8 x) = x))).

Parameter to_sint8: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint8'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-128%Z)%Z)%Z -> ((to_sint8 x) = (to_sint8 (x + 256%Z)%Z))) /\
  (~ (x < (-128%Z)%Z)%Z ->
   ((128%Z <= x)%Z -> ((to_sint8 x) = (to_sint8 (x - 256%Z)%Z))) /\
   (~ (128%Z <= x)%Z -> ((to_sint8 x) = x))).

Parameter to_uint16: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint16'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint16 x) = (to_uint16 (x + 65536%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((65536%Z <= x)%Z -> ((to_uint16 x) = (to_uint16 (x - 65536%Z)%Z))) /\
   (~ (65536%Z <= x)%Z -> ((to_uint16 x) = x))).

Parameter to_sint16: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint16'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-32768%Z)%Z)%Z -> ((to_sint16 x) = (to_sint16 (x + 65536%Z)%Z))) /\
  (~ (x < (-32768%Z)%Z)%Z ->
   ((32768%Z <= x)%Z -> ((to_sint16 x) = (to_sint16 (x - 65536%Z)%Z))) /\
   (~ (32768%Z <= x)%Z -> ((to_sint16 x) = x))).

Parameter to_uint32: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint32'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z -> ((to_uint32 x) = (to_uint32 (x + 4294967296%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((4294967296%Z <= x)%Z ->
    ((to_uint32 x) = (to_uint32 (x - 4294967296%Z)%Z))) /\
   (~ (4294967296%Z <= x)%Z -> ((to_uint32 x) = x))).

Parameter to_sint32: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint32'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-2147483648%Z)%Z)%Z ->
   ((to_sint32 x) = (to_sint32 (x + 4294967296%Z)%Z))) /\
  (~ (x < (-2147483648%Z)%Z)%Z ->
   ((2147483648%Z <= x)%Z ->
    ((to_sint32 x) = (to_sint32 (x - 4294967296%Z)%Z))) /\
   (~ (2147483648%Z <= x)%Z -> ((to_sint32 x) = x))).

Parameter to_uint64: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_uint64'def :
  forall (x:Numbers.BinNums.Z),
  ((x < 0%Z)%Z ->
   ((to_uint64 x) = (to_uint64 (x + 18446744073709551616%Z)%Z))) /\
  (~ (x < 0%Z)%Z ->
   ((18446744073709551616%Z <= x)%Z ->
    ((to_uint64 x) = (to_uint64 (x - 18446744073709551616%Z)%Z))) /\
   (~ (18446744073709551616%Z <= x)%Z -> ((to_uint64 x) = x))).

Parameter to_sint64: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom to_sint64'def :
  forall (x:Numbers.BinNums.Z),
  ((x < (-9223372036854775808%Z)%Z)%Z ->
   ((to_sint64 x) = (to_sint64 (x + 18446744073709551616%Z)%Z))) /\
  (~ (x < (-9223372036854775808%Z)%Z)%Z ->
   ((9223372036854775808%Z <= x)%Z ->
    ((to_sint64 x) = (to_sint64 (x - 18446744073709551616%Z)%Z))) /\
   (~ (9223372036854775808%Z <= x)%Z -> ((to_sint64 x) = x))).

Parameter two_power_abs: Numbers.BinNums.Z -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition is_uint (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) : Prop :=
  (0%Z <= x)%Z /\ (x < (two_power_abs n))%Z.

(* Why3 assumption *)
Definition is_sint (n:Numbers.BinNums.Z) (x:Numbers.BinNums.Z) : Prop :=
  ((-(two_power_abs n))%Z <= x)%Z /\ (x < (two_power_abs n))%Z.

Parameter to_uint:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Parameter to_sint:
  Numbers.BinNums.Z -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom is_to_uint8 : forall (x:Numbers.BinNums.Z), is_uint8 (to_uint8 x).

Axiom is_to_sint8 : forall (x:Numbers.BinNums.Z), is_sint8 (to_sint8 x).

Axiom is_to_uint16 : forall (x:Numbers.BinNums.Z), is_uint16 (to_uint16 x).

Axiom is_to_sint16 : forall (x:Numbers.BinNums.Z), is_sint16 (to_sint16 x).

Axiom is_to_uint32 : forall (x:Numbers.BinNums.Z), is_uint32 (to_uint32 x).

Axiom is_to_sint32 : forall (x:Numbers.BinNums.Z), is_sint32 (to_sint32 x).

Axiom is_to_uint64 : forall (x:Numbers.BinNums.Z), is_uint64 (to_uint64 x).

Axiom is_to_sint64 : forall (x:Numbers.BinNums.Z), is_sint64 (to_sint64 x).

Axiom id_uint8 :
  forall (x:Numbers.BinNums.Z), is_uint8 x -> ((to_uint8 x) = x).

Axiom id_sint8 :
  forall (x:Numbers.BinNums.Z), is_sint8 x -> ((to_sint8 x) = x).

Axiom id_uint16 :
  forall (x:Numbers.BinNums.Z), is_uint16 x -> ((to_uint16 x) = x).

Axiom id_sint16 :
  forall (x:Numbers.BinNums.Z), is_sint16 x -> ((to_sint16 x) = x).

Axiom id_uint32 :
  forall (x:Numbers.BinNums.Z), is_uint32 x -> ((to_uint32 x) = x).

Axiom id_sint32 :
  forall (x:Numbers.BinNums.Z), is_sint32 x -> ((to_sint32 x) = x).

Axiom id_uint64 :
  forall (x:Numbers.BinNums.Z), is_uint64 x -> ((to_uint64 x) = x).

Axiom id_sint64 :
  forall (x:Numbers.BinNums.Z), is_sint64 x -> ((to_sint64 x) = x).

Axiom id_uint8_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 256%Z)%Z ->
  ((to_uint8 x) = x).

Axiom id_sint8_inl :
  forall (x:Numbers.BinNums.Z), ((-128%Z)%Z <= x)%Z /\ (x < 128%Z)%Z ->
  ((to_sint8 x) = x).

Axiom id_uint16_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 65536%Z)%Z ->
  ((to_uint16 x) = x).

Axiom id_sint16_inl :
  forall (x:Numbers.BinNums.Z), ((-32768%Z)%Z <= x)%Z /\ (x < 32768%Z)%Z ->
  ((to_sint16 x) = x).

Axiom id_uint32_inl :
  forall (x:Numbers.BinNums.Z), (0%Z <= x)%Z /\ (x < 4294967296%Z)%Z ->
  ((to_uint32 x) = x).

Axiom id_sint32_inl :
  forall (x:Numbers.BinNums.Z),
  ((-2147483648%Z)%Z <= x)%Z /\ (x < 2147483648%Z)%Z -> ((to_sint32 x) = x).

Axiom id_uint64_inl :
  forall (x:Numbers.BinNums.Z),
  (0%Z <= x)%Z /\ (x < 18446744073709551616%Z)%Z -> ((to_uint64 x) = x).

Axiom id_sint64_inl :
  forall (x:Numbers.BinNums.Z),
  ((-9223372036854775808%Z)%Z <= x)%Z /\ (x < 9223372036854775808%Z)%Z ->
  ((to_sint64 x) = x).

Axiom proj_int8 :
  forall (x:Numbers.BinNums.Z), ((to_sint8 (to_uint8 x)) = (to_sint8 x)).

Axiom proj_int16 :
  forall (x:Numbers.BinNums.Z), ((to_sint16 (to_uint16 x)) = (to_sint16 x)).

Axiom proj_int32 :
  forall (x:Numbers.BinNums.Z), ((to_sint32 (to_uint32 x)) = (to_sint32 x)).

Axiom proj_int64 :
  forall (x:Numbers.BinNums.Z), ((to_sint64 (to_uint64 x)) = (to_sint64 x)).

Parameter L_strlen_1_:
  (addr -> Numbers.BinNums.Z) -> addr -> Numbers.BinNums.Z.

(* Why3 assumption *)
Definition shift_S40 (p:addr) (k:Numbers.BinNums.Z) : addr :=
  shift p (101%Z * k)%Z.

Axiom Q_strlen_pos_or_null :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  (x = 0%Z) -> (0%Z <= i)%Z -> is_sint8 x ->
  (forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z -> (i1 < i)%Z ->
   ~ ((Mchar (shift s i1)) = 0%Z)) ->
  ((L_strlen_1_ Mchar s) = i).

Axiom Q_strlen_neg :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr),
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z ->
   ~ ((Mchar (shift s i)) = 0%Z)) ->
  ((L_strlen_1_ Mchar s) < 0%Z)%Z.

Axiom Q_strlen_before_null :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  (0%Z <= i)%Z -> (i < (L_strlen_1_ Mchar s))%Z -> is_sint8 x -> ~ (x = 0%Z).

Axiom Q_strlen_at_null :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr),
  let x := L_strlen_1_ Mchar s in
  let x1 := Mchar (shift s x) in (0%Z <= x)%Z -> is_sint8 x1 -> (x1 = 0%Z).

Axiom Q_strlen_not_zero :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  let x1 := L_strlen_1_ Mchar s in
  ~ (x = 0%Z) -> (0%Z <= i)%Z -> (i <= x1)%Z -> is_sint8 x -> (i < x1)%Z.

Axiom Q_strlen_zero :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  let x1 := L_strlen_1_ Mchar s in
  (x = 0%Z) -> (0%Z <= i)%Z -> (i <= x1)%Z -> is_sint8 x -> (x1 = i).

Axiom Q_strlen_sup :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  let x1 := L_strlen_1_ Mchar s in
  (x = 0%Z) -> (0%Z <= i)%Z -> is_sint8 x -> (x1 <= i)%Z /\ (0%Z <= x1)%Z.

Axiom Q_strlen_shift :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := L_strlen_1_ Mchar s in
  (0%Z <= i)%Z -> (i <= x)%Z -> ((i + (L_strlen_1_ Mchar (shift s i)))%Z = x).

Axiom Q_strlen_create :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  let x1 := L_strlen_1_ Mchar s in
  (x = 0%Z) -> (0%Z <= i)%Z -> is_sint8 x -> (x1 <= i)%Z /\ (0%Z <= x1)%Z.

Axiom Q_strlen_create_shift :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z),
  let x := Mchar (shift s i) in
  let x1 := L_strlen_1_ Mchar (shift s k) in
  (x = 0%Z) -> (k <= i)%Z -> (0%Z <= k)%Z -> is_sint8 x ->
  (0%Z <= x1)%Z /\ ((k + x1)%Z <= i)%Z.

Parameter L_memcmp:
  (addr -> Numbers.BinNums.Z) -> (addr -> Numbers.BinNums.Z) -> addr ->
  addr -> Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom Q_memcmp_zero :
  forall (Mchar:addr -> Numbers.BinNums.Z) (Mchar1:addr -> Numbers.BinNums.Z)
    (s1:addr) (s2:addr) (n:Numbers.BinNums.Z),
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z -> (i < n)%Z ->
   ((Mchar1 (shift s1 i)) = (Mchar (shift s2 i)))) <->
  ((L_memcmp Mchar Mchar1 s1 s2 n) = 0%Z).

Axiom Q_memcmp_strlen_left :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s1:addr) (s2:addr)
    (n:Numbers.BinNums.Z),
  let x := L_strlen_1_ Mchar s1 in
  ((L_memcmp Mchar Mchar s1 s2 n) = 0%Z) -> (x < n)%Z ->
  ((L_strlen_1_ Mchar s2) = x).

Axiom Q_memcmp_strlen_right :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s1:addr) (s2:addr)
    (n:Numbers.BinNums.Z),
  let x := L_strlen_1_ Mchar s2 in
  ((L_memcmp Mchar Mchar s1 s2 n) = 0%Z) -> (x < n)%Z ->
  (x = (L_strlen_1_ Mchar s1)).

Axiom Q_memcmp_strlen_shift_left :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s1:addr) (s2:addr)
    (k:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := L_strlen_1_ Mchar s1 in
  let x1 := L_strlen_1_ Mchar s2 in
  ((L_memcmp Mchar Mchar s1 (shift s2 k) n) = 0%Z) -> (0%Z <= k)%Z ->
  (x < n)%Z -> (0%Z <= x1)%Z /\ (x1 <= (k + x)%Z)%Z.

Axiom Q_memcmp_strlen_shift_right :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s1:addr) (s2:addr)
    (k:Numbers.BinNums.Z) (n:Numbers.BinNums.Z),
  let x := L_strlen_1_ Mchar s2 in
  let x1 := L_strlen_1_ Mchar s1 in
  ((L_memcmp Mchar Mchar (shift s1 k) s2 n) = 0%Z) -> (0%Z <= k)%Z ->
  (x < n)%Z -> (0%Z <= x1)%Z /\ (x1 <= (k + x)%Z)%Z.

(* Why3 assumption *)
Definition P_valid_read_string
    (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (Mchar:addr -> Numbers.BinNums.Z) (s:addr) : Prop :=
  let x := L_strlen_1_ Mchar s in
  (0%Z <= x)%Z /\ valid_rd Malloc (shift s 0%Z) (1%Z + x)%Z.

Parameter L_wcslen_1_:
  (addr -> Numbers.BinNums.Z) -> addr -> Numbers.BinNums.Z.

Axiom Q_wcslen_pos_or_null :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  (x = 0%Z) -> (0%Z <= i)%Z -> is_sint32 x ->
  (forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z -> (i1 < i)%Z ->
   ~ ((Mint (shift s i1)) = 0%Z)) ->
  ((L_wcslen_1_ Mint s) = i).

Axiom Q_wcslen_neg :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr),
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z ->
   ~ ((Mint (shift s i)) = 0%Z)) ->
  ((L_wcslen_1_ Mint s) < 0%Z)%Z.

Axiom Q_wcslen_before_null :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  (0%Z <= i)%Z -> (i < (L_wcslen_1_ Mint s))%Z -> is_sint32 i ->
  is_sint32 x -> ~ (x = 0%Z).

Axiom Q_wcslen_at_null :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr),
  let x := L_wcslen_1_ Mint s in
  let x1 := Mint (shift s x) in (0%Z <= x)%Z -> is_sint32 x1 -> (x1 = 0%Z).

Axiom Q_wcslen_not_zero :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  let x1 := L_wcslen_1_ Mint s in
  ~ (x = 0%Z) -> (0%Z <= i)%Z -> (i <= x1)%Z -> is_sint32 i -> is_sint32 x ->
  (i < x1)%Z.

Axiom Q_wcslen_zero :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  let x1 := L_wcslen_1_ Mint s in
  (x = 0%Z) -> (0%Z <= i)%Z -> (i <= x1)%Z -> is_sint32 i -> is_sint32 x ->
  (x1 = i).

Axiom Q_wcslen_sup :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  let x1 := L_wcslen_1_ Mint s in
  (x = 0%Z) -> (0%Z <= i)%Z -> is_sint32 i -> is_sint32 x ->
  (x1 <= i)%Z /\ (0%Z <= x1)%Z.

Axiom Q_wcslen_shift :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := L_wcslen_1_ Mint s in
  (0%Z <= i)%Z -> (i <= x)%Z -> is_sint32 i ->
  ((i + (L_wcslen_1_ Mint (shift s i)))%Z = x).

Axiom Q_wcslen_create :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  let x1 := L_wcslen_1_ Mint s in
  (x = 0%Z) -> (0%Z <= i)%Z -> is_sint32 i -> is_sint32 x ->
  (x1 <= i)%Z /\ (0%Z <= x1)%Z.

Axiom Q_wcslen_create_shift :
  forall (Mint:addr -> Numbers.BinNums.Z) (s:addr) (i:Numbers.BinNums.Z)
    (k:Numbers.BinNums.Z),
  let x := Mint (shift s i) in
  let x1 := L_wcslen_1_ Mint (shift s k) in
  (x = 0%Z) -> (k <= i)%Z -> (0%Z <= k)%Z -> is_sint32 i -> is_sint32 k ->
  is_sint32 x -> (0%Z <= x1)%Z /\ ((k + x1)%Z <= i)%Z.

(* Why3 assumption *)
Definition P_valid_read_wstring
    (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (Mint:addr -> Numbers.BinNums.Z) (s:addr) : Prop :=
  let x := L_wcslen_1_ Mint s in
  (0%Z <= x)%Z /\ valid_rd Malloc (shift s 0%Z) (1%Z + x)%Z.

(* Why3 assumption *)
Definition P_valid_read_nstring (Init:addr -> Init.Datatypes.bool)
    (Malloc:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (Mchar:addr -> Numbers.BinNums.Z) (s:addr) (n:Numbers.BinNums.Z) : Prop :=
  P_valid_read_string Malloc Mchar s \/
  valid_rd Malloc (shift s 0%Z) n /\
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z -> (i < n)%Z ->
   ((Init (shift s i)) = Init.Datatypes.true)).

Parameter L_strcmp:
  (addr -> Numbers.BinNums.Z) -> addr -> addr -> Numbers.BinNums.Z.

Axiom Q_strcmp_zero :
  forall (Mchar:addr -> Numbers.BinNums.Z) (s1:addr) (s2:addr),
  let x := L_strlen_1_ Mchar s1 in
  ((L_strlen_1_ Mchar s2) = x) /\
  (forall (i:Numbers.BinNums.Z), (0%Z <= i)%Z -> (i <= x)%Z ->
   ((Mchar (shift s2 i)) = (Mchar (shift s1 i)))) <->
  ((L_strcmp Mchar s1 s2) = 0%Z).

(* Why3 goal *)
Theorem wp_goal :
  forall (t:addr -> Init.Datatypes.bool) (t1:addr -> Init.Datatypes.bool)
    (t2:Numbers.BinNums.Z -> Numbers.BinNums.Z)
    (t3:addr -> Numbers.BinNums.Z) (t4:addr -> Numbers.BinNums.Z)
    (i:Numbers.BinNums.Z) (a:addr) (a1:addr),
  let x := base a1 in
  let x1 := base a in
  let a2 := shift (shift_S40 (global 4454%Z) i) 0%Z in
  let a3 := shift a2 0%Z in
  let x2 := L_strlen_1_ t3 a in
  let a4 := memcpy t3 a3 t4 a3 49%Z in
  let a5 := memcpy t a3 t1 a3 49%Z in
  let a6 := shift a2 49%Z in
  ~ (x = 4454%Z) -> ~ (x1 = 4454%Z) -> (0%Z <= i)%Z ->
  ((region x) <= 0%Z)%Z -> ((region x1) <= 0%Z)%Z -> (i <= 1023%Z)%Z ->
  linked t2 -> sconst t3 -> scinit t -> is_sint32 i ->
  P_valid_read_nstring t t2 t3 a1 49%Z ->
  P_valid_read_nstring t t2 t3 a 49%Z ->
  separated a3 49%Z (shift a 0%Z) 49%Z ->
  ((x2 <= 48%Z)%Z -> ((L_strcmp a4 a3 a) = 0%Z)) ->
  ((49%Z <= x2)%Z -> ((L_memcmp a4 a4 a3 a 49%Z) = 0%Z)) ->
  (forall (i1:Numbers.BinNums.Z), (0%Z <= i1)%Z -> (i1 <= 48%Z)%Z ->
   ((a5 (shift a2 i1)) = Init.Datatypes.true)) ->
  P_valid_read_nstring (map.Map.set a5 a6 Init.Datatypes.true) t2
  (map.Map.set a4 a6 0%Z) a1 49%Z.
Proof.
intros t t1 t2 t3 t4 i a a1 x x1 a2 a3 x2 a4 a5 a6 h1 h2 h3 h4 h5 h6 h7 h8 h9
h10 h11 h12 h13 h14 h15 h16.
assert (Hb6 : base a6 = 4454%Z) by (unfold a6, a2, shift_S40, shift, global, base; reflexivity).
assert (Hb3 : base a3 = 4454%Z) by (unfold a3, a2, shift_S40, shift, global, base; reflexivity).
assert (Hba1 : forall k, base (shift a1 k) = base a1) by (intro k; unfold shift, base; reflexivity).
assert (Hfc : forall q, base q = base a1 -> (map.Map.set a4 a6 0%Z) q = t3 q).
{ intros q Hq.
  assert (Hqne : ~ (q = a6)).
  { intro He. apply h1. unfold x. rewrite <- Hq, He. exact Hb6. }
  rewrite (proj2 (map.Map.set'def a4 a6 0%Z q) Hqne).
  unfold a4.
  apply (proj1 (memcpy'def t3 a3 t4 a3 49%Z q)).
  right. right. left. rewrite Hq, Hb3. exact h1. }
assert (Hfi : forall q, base q = base a1 -> (map.Map.set a5 a6 Init.Datatypes.true) q = t q).
{ intros q Hq.
  assert (Hqne : ~ (q = a6)).
  { intro He. apply h1. unfold x. rewrite <- Hq, He. exact Hb6. }
  rewrite (proj2 (map.Map.set'def a5 a6 Init.Datatypes.true q) Hqne).
  unfold a5.
  apply (proj1 (memcpy'def t a3 t1 a3 49%Z q)).
  right. right. left. rewrite Hq, Hb3. exact h1. }
unfold P_valid_read_nstring in h11 |- *.
destruct h11 as [Hstr | [Hvrd Hinit]].
- left. unfold P_valid_read_string in Hstr |- *.
  destruct Hstr as [Hpos Hvrd].
  assert (HL : L_strlen_1_ (map.Map.set a4 a6 0%Z) a1 = L_strlen_1_ t3 a1).
  { apply Q_strlen_pos_or_null.
    - rewrite (Hfc (shift a1 (L_strlen_1_ t3 a1)) (Hba1 _)).
      apply Q_strlen_at_null. + exact Hpos.
      + admit. (* is_sint8 (t3 (shift a1 (strlen t3 a1))) -- NOT in WP context *)
    - exact Hpos.
    - rewrite (Hfc (shift a1 (L_strlen_1_ t3 a1)) (Hba1 _)).
      admit. (* is_sint8 ... again *)
    - intros i1 Hi1a Hi1b.
      rewrite (Hfc (shift a1 i1) (Hba1 _)).
      apply (Q_strlen_before_null t3 a1 i1 Hi1a Hi1b).
      admit. (* is_sint8 (t3 (shift a1 i1)) -- NOT in WP context *) }
  rewrite HL. split; assumption.
- right. split.
  + exact Hvrd.
  + intros i1 Hi1a Hi1b.
    rewrite (Hfi (shift a1 i1) (Hba1 _)).
    apply Hinit; assumption.
Admitted.

